Главный сервис
Max-Jordan/java-explore-with-me pull request #5
Opened 2023-04-05 18:06 UTC by Max-Jordan

2023-04-08 12:54 UTC, Frilock requested changes
Добрый день, от меня особой критики нет. Конечно еще раз надо будет посмотреть, когда вы сборку поправите, но пока особо нет критики

2023-04-08 12:54 UTC, Frilock commented on .gitignore
> +**/.DS_Store
Необходимо получить сборку с пройденными тестами

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/category/CategoryRepository.java
> +@Repository
Писал вроде - Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-04-08 12:54 UTC, Frilock commented on main/pom.xml
>          </dependency>
Вообще не обратил внимание раньше, но называть подмодуль - main, не особо хорошая идея. У него же есть какое то название и функции, main совсем уж как то просто =)

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/MainApp.java
> +    public RestTemplate getRestTemplate() {
А зачем Вам эти бины тут?

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
Транзакцию нигде не пропустили?

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/event/EventControllerForAdmin.java
> +
Лишний пропуск строки

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/event/EventRepository.java
> +@Repository
Лишняя аннотация

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/event/EventServiceImpl.java
> +                    if (!event.getState().equals(StatusEvent.PENDING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/event/EventServiceImpl.java
> +                repository.findEventByAvailable(text, paid, rangeStart, rangeEnd, categories, makePageable(from, size))
лучше в названии бы указать не event, a events, ведь возвращается не 1 запись. Путает

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private static Object makeEventObject(Object to, Object from) {
сильно

2023-04-08 12:54 UTC, Frilock commented on main/src/main/java/ru/practicum/request/RequestRepository.java
> +@Repository
Лишняя

2023-04-08 12:54 UTC, Frilock commented on main/src/main/resources/schema.sql
> +    name_user VARCHAR(255)                            NOT NULL,
Мне кажется стоит к выбору размерности подходить более серьезно, врядли например емейл может быть 255 символов. Кроме того эти значения нужно указыывать в аннотации column. Там size вроде параметр называется.
Это нужно чтобы вы в коде могли размерность полей понимать, не лазя в БД

2023-04-08 16:53 UTC, Max-Jordan commented on main/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private static Object makeEventObject(Object to, Object from) {
Старался как мог))

2023-04-08 16:53 UTC, Max-Jordan commented on main/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private static Object makeEventObject(Object to, Object from) {
Надеюсь, что это действительно достойно выглядит)

2023-04-08 17:01 UTC, Max-Jordan commented on main/src/main/java/ru/practicum/MainApp.java
> +    public RestTemplate getRestTemplate() {
Без этого Бина не запускается приложение.

2023-04-10 18:05 UTC, Frilock requested changes
Добрый вечер, еще пара комментариев =)

2023-04-10 18:05 UTC, Frilock commented on docker-compose.yml
> +      - STATISTIC_SERVER_URL=http://stats-server:9090
Большая просьба называть коммиты адекватно. Либо сквашить их. Сейчас это выглядит не серьезно.

2023-04-10 18:05 UTC, Frilock commented on main/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +@Transactional
Если ты ставишь аннотацию на методы то она не нужна тебе на классе. И наоборот, если она у тебя стоит над классом то она будет на всех публичных методах этого класса.
Вообще транзакции очень важная тема, ее будут точно спрашивать на собеседованиях. Формально, чтоб я отстал тебе надо ее убрать либо с методов и оставить над классом, либо наоборот, но вообще большой совет погрузиться более подробно в эту тему

2023-04-10 18:05 UTC, Frilock commented on statistic/statistic_service/src/main/java/ru/practicum/statistics/model/ViewStat.java
> +    public ViewStat(String app, String uri, long hits) {
А смысл убирать AllArgs...? Одно и тоже ведь

2023-04-11 05:08 UTC, Frilock approved these changes
Принял, успехов

2023-04-11 09:06 UTC, merged